### ISSUE TITLE
Soundtrap Data Download

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-field-methods#13]
Do we want to include both methods for downloading data from the Soundtraps and specify which models are compatible with each of the methods? Right now I only documented how to download by plugging in the Soundtrap

https://github.com/SAEL-SWFSC/adrift-field-methods/blob/33713adfee4dd34a940a5d76a0e08e3751ee164c/content/Data-Download.qmd#L17-L33

**Comment by chomweaverNOAA** [comment]
I would specify methods for both soundtrap models.

**Comment by Kourtney-Burger** [comment]
Field Methods manual is updated with this change
