### ISSUE TITLE
ADRIFT Field Methods Videos

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-field-methods#14]
We currently have our deployment/recovery videos in our Field Methods linked to a google drive. Moving towards open science practices, we want the videos to be more accessible and not have to give people permission to view them. So far, we have ruled out the following ideas; 
- Can't post to lab youtube account or vimeo
- Video files are too large to store them directly on GitHub

**Comment by Kourtney-Burger** [comment]
@shannonrankin Eli mentioned we might be able to post videos from a personal youtube account and link to them in our doc, is this a possibility? I know that goes back to our convo that different centers have different rules but just thought I would see if this is a possible solution

**Comment by shannonrankin** [comment]
I reached out to the contact person on this to get their recommendation (I had a meeting with her last year, and I was firmly told that I may NOT use youtube). I ran into a lot of other problems with youtube the other year as well-- so I'm going to see what other options there may be. So-- standby. Hopefully I'll get a response from Courtney in the next week-- but please ping me if more than 2 weeks have gone by!

**Comment by Kourtney-Burger** [comment]
Based on convo w/ Shannon on 1/12/23. We will move forward with using Camtasia to edit our videos, following some NOAA specific guidelines (captioning, general standards, etc.). I will set up Camtasia template with one of our old videos and send to Courtney Groeneveld for feedback/approval. Once that is completed we will move forward with setting up a video page on our website and make the rest of the videos.

@shannonrankin Can you send me the Camtasia license information?

**Comment by shannonrankin** [comment]
I *think* I have two licenses: 
      Product: Camtasia Government
      Key(s): CEB5L-9YCCD-LUHHH-XC8Z9-W5B2R
      https://www.techsmith.com/download/oldversions

      Product: Camtasia Government
      Key(s): CPJZC-2KHAH-CGUWF-X46XF-CD94C
      https://www.techsmith.com/download/licenses/camtasia/20

One of them is on my desktop computer (so it is accessible to anyone). The other one was on my previous laptop, but I forgot to remove the key before cleaning the computer during the switches. Perhaps you can see (1) which key is used on the desktop and (2) try to use the other to install camtasia on your laptop. It may not be this easy, but if you can give it a try?

**Comment by chomweaverNOAA** [comment]
I had to do this about a year ago and this is what TechSmith said...

Thank you for contacting TechSmith Technical Support.

To transfer the license key you only need to install Camtasia on the new device and enter the software key. You can download Camtasia with this link. https://download.techsmith.com/camtasiastudio/releases/20014/camtasia.exe If you get an error similar to exceeding or reaching the maximum number of installations he may follow the step in this article to reset the number of activations of the software key from our servers. https://support.techsmith.com/hc/en-us/articles/360040240491

**Comment by Kourtney-Burger** [comment]
@shannonrankin Can you check which version of Camtasia is being used for this Key(s): CEB5L-9YCCD-LUHHH-XC8Z9-W5B2R

**Comment by Kourtney-Burger** [comment]
Your desktop is using  

Product: Camtasia Government
Key(s): CPJZC-2KHAH-CGUWF-X46XF-CD94C
https://www.techsmith.com/download/licenses/camtasia/20

with version 20.0.14

**Comment by Kourtney-Burger** [comment]
Both Camtasia keys are working, one on Shannon's desktop and one on my personal laptop
