### ISSUE TITLE
Add dimensions to description of hardware

### ISSUE THREAD

**Issue by asimonis** [SAEL-SWFSC/adrift-field-methods#15]
It would be helpful to list length, width, height and weight for buoy components, where available.  Some info available here: https://docs.google.com/document/d/1hfyNvf3UHqaqrjo3fhyjRUK-QzXepL3oa4cdqXrPcxA/edit

**Comment by Kourtney-Burger** [comment]
Thanks for sharing that info! I just added everything on that doc to [this page](https://sael-swfsc.github.io/adrift-field-methods/content/Hardware-PoleBuoy.html) and I will keep this issue open to add additional info for buoy components as needed

**Comment by Kourtney-Burger** [comment]
Closing issue - this information has been moved [here](https://sael-swfsc.github.io/adrift-field-methods/content/Hardware-PoleBuoy-Build.html)
