### ISSUE TITLE
Cannot embed video

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-field-methods#2]
I tried 2 different methods to embed a video of our deployment and couldn't get either to show up on the rendered qmd. 
Please help! 

https://github.com/SAEL-SWFSC/adrift-field-methods/blob/80d8940a147d5fdb137d282e3a58bf7030b14215/content/Field-Deployment.qmd#L13-L15

I used a video from our youtube channel as an example

**Comment by TaikiSan21** [comment]
Looks like the video feature only works with Quarto > 1.2.0, but these versions are all in pre-relase. Current release version is only [1.1.2](https://quarto.org/docs/download/release.html) as of 10/27/2022. We can modify the GitHub Action to use pre-release versions of Quarto if we want to use the video feature now, but there is potential for pre-release versions to have wonky bugs. Or we can just wait til 1.2.0 is officially released.

See [here](https://github.com/quarto-dev/quarto-actions/tree/main/setup) for info on setting Quarto version for the Action

**Comment by Kourtney-Burger** [comment]
Thanks Taiki, that's good to know. We can leave them as links for now instead of trying to integrate them into the document

**Comment by Kourtney-Burger** [comment]
We will revisit this once the new version of Quarto is released
