### ISSUE TITLE
Create Sections in ADRIFT Field Methods 

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/adrift-field-methods#3]
Create sections for adrift field methods in yaml so that the web-book has an expandable contents on the left side. Two sections now include: Hardware and Field Methods

See the _quarto.yaml for the lab manual (https://github.com/SAEL-SWFSC/SAEL-lab-manual) for how this is set up (Shannon did this for the Open Science section).

**Comment by Kourtney-Burger** [comment]
Just finished this!

**Comment by Kourtney-Burger** [comment]
Just finished this
