### ISSUE TITLE
Add personnel requirements to retrieval info

### ISSUE THREAD

**Issue by asimonis** [SAEL-SWFSC/adrift-field-methods#4]
I think it would be helpful to outline the personnel needs (at least two people) and roles for recovery (someone to pull, store gear, watch for drogue/hydrophones coming up). Number of people may be different on a large ship vs. small boat.  

https://github.com/SAEL-SWFSC/adrift-field-methods/blob/cdc542dbf569d1b9903241e7ebe41bc7868d2a1b/content/Field-Retrieval.qmd#L5-L9

**Comment by Kourtney-Burger** [comment]
How does this sound?

https://github.com/SAEL-SWFSC/adrift-field-methods/blob/ebd4ad01932ea696e86e59bf45afd41c4721889f/content/Field-Retrieval.qmd#L5-L11

**Comment by Kourtney-Burger** [comment]
I wasn't sure about the role part, if it fully makes sense. Let me know what edits you have

**Comment by asimonis** [comment]
Looks good to me!
