### ISSUE TITLE
Add note to confirm LED status prior to deployment

### ISSUE THREAD

**Issue by asimonis** [SAEL-SWFSC/adrift-field-methods#5]
Need to add a note about a final check to confirm Sound Trap status prior to closing it up... 

I'm not sure exactly where you want this to go [(maybe here ](https://github.com/SAEL-SWFSC/adrift-field-methods/blob/9d61fe57d01d77cd2b5e80ebf5a538765d803172/content/Field-Deployment-Preparation.qmd#L9), but here's some sample text: 
**Final Check**
Confirm the status of the Sound Trap after it is programmed. After a ST640 is programmed and disconnected from a laptop, the LED should flash red to indicate it is programmed to start at a later time. The LED will flash green if it is actively recording. If the LED does not flash at all after the Sound Trap is disconnected, it must be re-connected to the laptop and re-programmed.

**Comment by Kourtney-Burger** [comment]
Thanks Anne, I just updated this here https://github.com/SAEL-SWFSC/adrift-field-methods/blob/5cdb16b2ead0a8467334d40085e849ce982784a4/content/Field-Deployment-Preparation.qmd#L10-L12
