### ISSUE TITLE
Add information on data download

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-field-methods#6]
Need to add info to [this qmd](https://github.com/SAEL-SWFSC/adrift-field-methods/blob/5cdb16b2ead0a8467334d40085e849ce982784a4/content/Data-Download.qmd) on HOW to download data (with links to pages on how to download data from recorder, sensus, etc), and how to save/ship the data to us so it can be uploaded

**Comment by shannonrankin** [comment]
Completed draft entry on this, including preparing the hard drive, downloading soundtrap & depth data, and shipping the data. There is also a section in there for completing the Deployment Details metadata-- this needs additional help.

**Comment by Kourtney-Burger** [comment]
I can't think of anything else that would need to be added to the deployment details when the data is downloaded and shipped. I added all of that information in the metadata qmd for each step of the process. Let me know if I am missing something
