### ISSUE TITLE
Data Downloads: Add info re: Metadata

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/adrift-field-methods#7]
Draft 'Data Downloads' part of the manual has a space for :
Deployment Data- Google Drive
Go to Deployment Google Folder & fill in any final data regarding the deployment
[Note: NEED TO WORK ON THIS!]

- [x] Perhaps rename this section?
- [ ] Need to identify ALL fields that should be checked & updated (Deployment details), as well as information on how to access deployment details

**Comment by Kourtney-Burger** [comment]
I linked the deployment details spreadsheet and renamed the section. Is it enough to say something like "Ensure all fields are filled in on the deployment details spreadsheet" or do we want to list all of the fields. 

I also put specific information on which columns to fill in during prep/deployment/retrieval on the metadata qmd

**Comment by shannonrankin** [comment]
Hmmmm.... I suppose we should trust that they will fill them all out, yes? I might add in that they may need to revise the deploy/retrieve start/end time (sometimes they put in starter information to get the maps going, but then we need to make sure we revise it based on the actual start/end time).  If explaining the obvious is too much, then keep it just to the reminders of things that *might* be missed...

**Comment by Kourtney-Burger** [comment]
How is this? 
https://github.com/SAEL-SWFSC/adrift-field-methods/blob/0a2d2d218c22b3feb6611bab85c8eb372c2cd86c/content/Data-Download.qmd#L59-L67

**Comment by shannonrankin** [comment]
Perfect! Love it-- thanks. If all is well, go ahead & close this issue. 
:)
