### ISSUE TITLE
Put links at top of page to sections further down on page

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/adrift-field-methods#8]
For the Data Download page-- I think it makes sense to keep it all as one page, but there are a few sections identified. I think it would be helpful to identify these sections at the top (identify all the bits that need to be completed during this stage), and then have links to those sections up at the top. This is similar to how you did it on the google drive, but I'm not (yet) sure how to do this here, so making this an issue for one of us to resolve!

**Comment by Kourtney-Burger** [comment]
On the left side of the page it has the section headers linked (under 'On this page'). Is this good or do you still want me to link the sections in a different way?

**Comment by shannonrankin** [comment]
Oh! You mean on the 'right-hand side', correct?
I never saw that before! Yes, that should be fine (as long as others see what I missed!)
:)

Will close this issue. Thanks!

**Comment by Kourtney-Burger** [comment]
Oh yes right hand side! 

Something about me is I ALWAYS mess up my right and left, people always call me out for it. Sorry about that!

**Comment by shannonrankin** [comment]
We all have our things... no worries. I have a LOT of little things  
:)
